version: "3.9"
services:
  magiweb:
    restart: always
    depends_on:
       - mysqldb
    image: magiweb_ui
    build: .
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${MAGI_WEB_PORT}:80
  mysqldb:
    image: mysql:8.0.21
    restart: always
    volumes:
      - /var/mysql_data/${MYSQL_VOLUME_PATH:-magi_live}_${MAGI_WEB_PORT}_${MYSQL_PORT}:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: magi
      MYSQL_DATABASE: financevisualization
      MYSQL_USER: samet
      MYSQL_PASSWORD: 1234
    ports:
      - ${MYSQL_PORT}:3306
